### ISSUE TITLE
USER STORY: Easy Product Browsing and Selection

### ISSUE THREAD

**Issue by KimBergstroem** [KimBergstroem/PP5#12]
## Description: 

**EPIC:** **#3**

**As a shopper**, I want to easily browse through a list of products and be able to select the ones I want to purchase.

## Acceptance Criteria: 

- **Acceptance Criteria 1:** As a shopper, I can see a list of products on the homepage.
- **Acceptance Criteria 2:** I can easily select multiple products from the navigation menu.
- **Acceptance Criteria 3:** The product should have an "add to bag" button for easy purchase.

## Tasks: 

- [x] Implement a product listing navigation bar menu on the homepage.
- [x] Add a "Add to Cart" button to each product.
- [x] Ensure selected products are correctly added to the shopping cart.

**Comment by KimBergstroem** [comment]
Add to cart button is fixed in every product, and also quantity button.
