### ISSUE TITLE
USER STORY: Product Size and Quantity Selection

### ISSUE THREAD

**Issue by KimBergstroem** [KimBergstroem/PP5#24]
### Description:

**EPIC: #6**

**As a shopper**, I want to select the desired size, sort, color and quantity of a product when making a purchase to avoid any accidental errors.

### Acceptance Criteria:

- **Acceptance Criteria 1:** When adding a product to the shopping cart, I can specify the desired information from available options.
- **Acceptance Criteria 2:** I can choose the quantity of the product to be added to the cart.
- **Acceptance Criteria 3:** The selected size and quantity are clearly visible in the shopping cart.

### Tasks:

- [x] Implement a product feature pick menu selection feature.
- [x] Develop a quantity selection option for product items.
- [x] Ensure that the selected information and quantity are clearly displayed in the shopping cart.

**Comment by KimBergstroem** [comment]
We decided to not implement the size option, as we are only selling electronic products for the moment. This can be a feature implementation.
